name: flexlm shell checker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check syntax script
        id: syntax_checker
        run: |
           bash -n sh_tool/bin/flexlm.sh && script_1=0 || script_1=1
           bash -n sh_tool/bin/check_license.sh && script_2=0 || script_2=1
           bash -n sh_tool/bin/load_licenses.sh && script_3=0 || script_3=1
           bash -n sh_tool/bin/start_license.sh && script_4=0 || script_4=1
           bash -n sh_tool/bin/stop_license.sh && script_5=0 || script_5=1
           [[ $script_1 -eq 0 && $script_2 -eq 0 && $script_3 -eq 0 && $script_4 -eq 0 && $script_5 -eq 0 ]] && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check size script
        id: size_checker
        run: |
          echo Checking size
          code_line_number_1=$(wc -l < sh_tool/bin/flexlm.sh)
          code_line_number_2=$(wc -l < sh_tool/bin/check_license.sh)
          code_line_number_3=$(wc -l < sh_tool/bin/load_licenses.sh)
          code_line_number_4=$(wc -l < sh_tool/bin/start_license.sh)
          code_line_number_5=$(wc -l < sh_tool/bin/stop_license.sh)
          [[ $code_line_number_1 -gt 300 || $code_line_number_2 -gt 300 || $code_line_number_3 -gt 300 || $code_line_number_4 -gt 300 || $code_line_number_5 -gt 300 ]] && echo ::set-output name=status::failure || echo ::set-output name=status::success
      - name: Check on failures
        if: steps.syntax_checker.outputs.status == 'failure' || steps.size_checker.outputs.status == 'failure'
        run: exit 1
